INSERT Teams (TeamId, Team_Name, Place, Zone, Contact, IsRegistered, City) VALUES (1, N'Gulzar Cricket Club', N'Malir City', N'4', N'03353928246', 0, N'Karachi')
INSERT Teams (TeamId, Team_Name, Place, Zone, Contact, IsRegistered, City) VALUES (2, N'Pak Shaheen c c', N'MALIR', N'4', N'0337-3167977', 0, N'Karachi')
INSERT Teams (TeamId, Team_Name, Place, Zone, Contact, IsRegistered, City) VALUES (3, N'Inqilab Cricket Club', N'QUAIDABAD', N'4', N'0313-2276376', 0, N'Karachi')
INSERT Teams (TeamId, Team_Name, Place, Zone, Contact, IsRegistered, City) VALUES (4, N'Tuba Sports c c', N'RAFY AHAM', N'4', NULL, 0, N'Karachi')
INSERT Teams (TeamId, Team_Name, Place, Zone, Contact, IsRegistered, City) VALUES (5, N'Union Sports c c ', N'MALIR HALT', N'4', NULL, 0, N'Karachi')
INSERT Teams (TeamId, Team_Name, Place, Zone, Contact, IsRegistered, City) VALUES (6, N'Hansabad GYM', N'MALIR', N'4', NULL, 1, N'Karachi')
INSERT Teams (TeamId, Team_Name, Place, Zone, Contact, IsRegistered, City) VALUES (7, N'Orient Star C C', N'MALIR', N'4', NULL, 1, N'Karachi')
INSERT Teams (TeamId, Team_Name, Place, Zone, Contact, IsRegistered, City) VALUES (8, N'Hansot GYM', N'SHAH FAISEL', N'4', NULL, 1, N'Karachi')
INSERT Teams (TeamId, Team_Name, Place, Zone, Contact, IsRegistered, City) VALUES (9, N'Bright Cricket Club', N'PIA Colony', N'4', NULL, 1, N'Karachi')
INSERT Teams (TeamId, Team_Name, Place, Zone, Contact, IsRegistered, City) VALUES (10, N'Young Pak Flag', N'Malir ', N'4', NULL, 0, N'Karachi')
INSERT Teams (TeamId, Team_Name, Place, Zone, Contact, IsRegistered, City) VALUES (11, N'Millat Cricket Club ', N'Shah Faisal ', N'4', NULL, 1, N'Karachi')
INSERT Teams (TeamId, Team_Name, Place, Zone, Contact, IsRegistered, City) VALUES (12, N'Faisal Gym C C', N'Shah faisal', N'4', NULL, 1, N'Karachi')
INSERT Teams (TeamId, Team_Name, Place, Zone, Contact, IsRegistered, City) VALUES (13, N'Saudabad Gym', N'MALIR', N'4', NULL, 1, N'Karachi')
INSERT Teams (TeamId, Team_Name, Place, Zone, Contact, IsRegistered, City) VALUES (14, N'Sind Rana C C', N'Quaidabad', N'4', NULL, 1, N'Karachi')
INSERT Teams (TeamId, Team_Name, Place, Zone, Contact, IsRegistered, City) VALUES (15, N'Quaidabad Gym', N'Quaidabad ', N'4', NULL, 1, N'Karachi')
INSERT Teams (TeamId, Team_Name, Place, Zone, Contact, IsRegistered, City) VALUES (16, N'Steel town Gym', N'STEEL TOWN', N'4', NULL, 0, N'Karachi')
INSERT Teams (TeamId, Team_Name, Place, Zone, Contact, IsRegistered, City) VALUES (17, N'Karachi Eglets c c', N'PIA Colony', N'4', NULL, 0, N'Karachi')
